# Generated by Django 6.0.5 on 2026-06-18 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.progreso')),
            ],
        ),
    ]
