# Generated by Django 6.0.5 on 2026-06-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0002_historialactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='palabra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
