# Generated by Django 6.0.5 on 2026-06-21 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0003_progreso_palabra'),
    ]

    operations = [
        migrations.RunSQL("""

        -- TRIGGER FUNCTION
        CREATE OR REPLACE FUNCTION registrar_historial()
        RETURNS TRIGGER AS
        $$
        BEGIN
            INSERT INTO aprendizaje_historialactividad
            (
                progreso_id,
                fecha_registro
            )
            VALUES
            (
                NEW.id,
                CURRENT_TIMESTAMP
            );

            RETURN NEW;
        END;
        $$
        LANGUAGE plpgsql;

        -- TRIGGER
        CREATE TRIGGER trg_registrar_historial
        AFTER INSERT
        ON aprendizaje_progreso
        FOR EACH ROW
        EXECUTE FUNCTION registrar_historial();

        -- VIEW
       CREATE OR REPLACE VIEW vw_progreso_usuarios AS
       SELECT
          u.id AS usuario_id,
          u.nombre AS usuario,
          a.nombre_actividad AS actividad,
          p.palabra,
          p.resultado,
          p.fecha_realizacion
       FROM aprendizaje_progreso p
       INNER JOIN aprendizaje_usuario u
          ON p.usuario_id = u.id
       INNER JOIN aprendizaje_actividad a
       ON p.actividad_id = a.id;

        """)
    ]
